// Maps asset key → static require. Add one line per delivered PNG.
// Metro can't require() a dynamic string path, so each PNG needs an explicit
// entry here. Until a key has an entry, ArtSlot renders its procedural placeholder.
export const ART: Record<string, number> = {
  'start_hero': require('./start_hero.png'),
  'event_acquihire_offer': require('./event_acquihire_offer.png'),
  'event_agency_expansion': require('./event_agency_expansion.png'),
  'event_apprenticeship_offer': require('./event_apprenticeship_offer.png'),
  'event_bigco_alumni_referral': require('./event_bigco_alumni_referral.png'),
  'event_bigco_full_time_offer': require('./event_bigco_full_time_offer.png'),
  'event_bigco_internship': require('./event_bigco_internship.png'),
  'event_burnout_recovery_event': require('./event_burnout_recovery_event.png'),
  'event_burnout_relapse_warning': require('./event_burnout_relapse_warning.png'),
  'event_burnout_warning': require('./event_burnout_warning.png'),
  'event_career_layoff_no_fund': require('./event_career_layoff_no_fund.png'),
  'event_career_layoff_with_fund': require('./event_career_layoff_with_fund.png'),
  'event_corporate_leadership_offer': require('./event_corporate_leadership_offer.png'),
  'event_drop_out_decision': require('./event_drop_out_decision.png'),
  'event_dropped_out_grit_opportunity': require('./event_dropped_out_grit_opportunity.png'),
  'event_emergency_fund_decision': require('./event_emergency_fund_decision.png'),
  'event_etf_recurring_uplift': require('./event_etf_recurring_uplift.png'),
  'event_find_mentor': require('./event_find_mentor.png'),
  'event_finished_degree_consulting_role': require('./event_finished_degree_consulting_role.png'),
  'event_first_brokerage': require('./event_first_brokerage.png'),
  'event_first_campus_job': require('./event_first_campus_job.png'),
  'event_first_freelance_client': require('./event_first_freelance_client.png'),
  'event_first_freelance_referral': require('./event_first_freelance_referral.png'),
  'event_first_tuition_bill': require('./event_first_tuition_bill.png'),
  'event_founder_scaling_decision': require('./event_founder_scaling_decision.png'),
  'event_freelance_retainer': require('./event_freelance_retainer.png'),
  'event_independent_brand_launch': require('./event_independent_brand_launch.png'),
  'event_inflated_lifestyle_trap': require('./event_inflated_lifestyle_trap.png'),
  'event_lifestyle_inflation_apartment': require('./event_lifestyle_inflation_apartment.png'),
  'event_lifestyle_temptation': require('./event_lifestyle_temptation.png'),
  'event_loan_consolidation_offer': require('./event_loan_consolidation_offer.png'),
  'event_loan_repayment_notice': require('./event_loan_repayment_notice.png'),
  'event_major_choice': require('./event_major_choice.png'),
  'event_manager_conflict': require('./event_manager_conflict.png'),
  'event_market_dip_buy': require('./event_market_dip_buy.png'),
  'event_mentor_role_intro': require('./event_mentor_role_intro.png'),
  'event_mentor_warm_intro': require('./event_mentor_warm_intro.png'),
  'event_networking_event': require('./event_networking_event.png'),
  'event_overtime_spiral': require('./event_overtime_spiral.png'),
  'event_parental_support_offer': require('./event_parental_support_offer.png'),
  'event_promotion_review': require('./event_promotion_review.png'),
  'event_property_deal': require('./event_property_deal.png'),
  'event_sabbatical_window': require('./event_sabbatical_window.png'),
  'event_scholarship_offer': require('./event_scholarship_offer.png'),
  'event_side_project_milestone': require('./event_side_project_milestone.png'),
  'event_side_project_window': require('./event_side_project_window.png'),
  'event_skill_upgrade_certificate': require('./event_skill_upgrade_certificate.png'),
  'event_startup_offer': require('./event_startup_offer.png'),
  'event_studio_launch': require('./event_studio_launch.png'),
  'event_trade_promotion': require('./event_trade_promotion.png'),
  'event_universal_cross_pull': require('./event_universal_cross_pull.png'),
  'event_university_income_relief_debt': require('./event_university_income_relief_debt.png'),
  'event_university_income_relief_lowsalary': require('./event_university_income_relief_lowsalary.png'),
  'event_university_income_relief_stress': require('./event_university_income_relief_stress.png'),
  'event_vocational_certification': require('./event_vocational_certification.png'),
  'event_warehouse_role': require('./event_warehouse_role.png'),
  'event_whats_next': require('./event_whats_next.png'),
  'event_where_you_live': require('./event_where_you_live.png'),
  'phase_career': require('./phase_career.png'),
};

export const hasArt = (key?: string): boolean => !!key && key in ART;
